---
builds:
  - id: agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    dir: agent
    main: agent.go
    binary: agent
    flags:
      - -trimpath
    ldflags: -s -w
  - id: insight
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    dir: example
    main: example.go
    binary: insight
    flags:
      - -trimpath
    ldflags: -s -w

changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
