---
builds:
  - id: insight
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    dir: example
    main: main.go
    binary: insight
    flags:
      - -trimpath
    ldflags: -s -w

changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
