apiVersion: v1
kind: insight
metadata:
  name: insight
spec:
  buildsight:
    file:
      - name: string
        content: base64
    path:
      - name: string
        path: /path/to/file
  codesight:
    file:
      - name: string
        content: base64
    path:
      - name: string
        path: /path/to/file
  gptsight:
    file:
      - name: string
        content: base64
    path:
      - name: string
        path: /path/to/file
    gpt:
      - name: string
        url: 127.0.0.1:8080
        user: user
        pass: pass
